// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentApplicationModel.Data;

#nullable disable

namespace StudentApplication.Migrations
{
    [DbContext(typeof(PrimaryContext))]
    [Migration("20241205225549_IntialCreate")]
    partial class IntialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Applicant", b =>
                {
                    b.Property<int>("ApplicantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicantID"));

                    b.Property<string>("ApplicationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAONumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CampusID")
                        .HasColumnType("int");

                    b.Property<string>("CourseSelectionReasons")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentClub")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateSubmitted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighestCompetitionLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeclarationConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PastClubs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredLeisurewearSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PriorThirdLevelAttendance")
                        .HasColumnType("bit");

                    b.Property<int?>("ScholarshipID")
                        .HasColumnType("int");

                    b.Property<string>("SecondarySchoolAttended")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SportPositionOrCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SportingAchievements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SportingGoals")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApplicantID");

                    b.HasIndex("CAONumber")
                        .IsUnique();

                    b.HasIndex("CampusID");

                    b.HasIndex("ScholarshipID");

                    b.ToTable("Applicants");
                });

            modelBuilder.Entity("ContactDetail", b =>
                {
                    b.Property<int>("ContactID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactID"));

                    b.Property<int>("ApplicantID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentsEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentsPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactID");

                    b.HasIndex("ApplicantID")
                        .IsUnique();

                    b.ToTable("ContactDetails");
                });

            modelBuilder.Entity("CourseCode", b =>
                {
                    b.Property<int>("CourseCodeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseCodeID"));

                    b.Property<int>("ApplicantID")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseCodeID");

                    b.HasIndex("ApplicantID");

                    b.ToTable("CourseCodes");
                });

            modelBuilder.Entity("HomeDetail", b =>
                {
                    b.Property<int>("HomeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HomeID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ApplicantID")
                        .HasColumnType("int");

                    b.HasKey("HomeID");

                    b.HasIndex("ApplicantID")
                        .IsUnique();

                    b.ToTable("HomeDetails");
                });

            modelBuilder.Entity("Referee", b =>
                {
                    b.Property<int>("RefereeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefereeID"));

                    b.Property<int>("ApplicantID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleOrRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RefereeID");

                    b.HasIndex("ApplicantID");

                    b.ToTable("Referees");
                });

            modelBuilder.Entity("StudentApplicationModel.Models.ApplicantSport", b =>
                {
                    b.Property<int>("ApplicantID")
                        .HasColumnType("int");

                    b.Property<int>("SportID")
                        .HasColumnType("int");

                    b.HasKey("ApplicantID", "SportID");

                    b.HasIndex("SportID");

                    b.ToTable("ApplicantSports");
                });

            modelBuilder.Entity("StudentApplicationModel.Models.Campus", b =>
                {
                    b.Property<int>("CampusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CampusID"));

                    b.Property<string>("CampusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CampusID");

                    b.ToTable("Campuses");
                });

            modelBuilder.Entity("StudentApplicationModel.Models.Scholarship", b =>
                {
                    b.Property<int>("ScholarshipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScholarshipID"));

                    b.Property<string>("OtherDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScholarshipTypeID")
                        .HasColumnType("int");

                    b.HasKey("ScholarshipID");

                    b.HasIndex("ScholarshipTypeID");

                    b.ToTable("Scholarships");
                });

            modelBuilder.Entity("StudentApplicationModel.Models.ScholarshipApplication", b =>
                {
                    b.Property<int>("ApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationID"));

                    b.Property<int>("ApplicantID")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ApplicationID");

                    b.HasIndex("ApplicantID");

                    b.ToTable("ScholarshipApplications");
                });

            modelBuilder.Entity("StudentApplicationModel.Models.ScholarshipOfferHistory", b =>
                {
                    b.Property<int>("OfferID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfferID"));

                    b.Property<int>("ApplicantID")
                        .HasColumnType("int");

                    b.Property<int?>("CampusID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OfferDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResponseStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScholarshipID")
                        .HasColumnType("int");

                    b.Property<int>("SportID")
                        .HasColumnType("int");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OfferID");

                    b.HasIndex("ScholarshipID");

                    b.HasIndex("SportID");

                    b.HasIndex("ApplicantID", "ScholarshipID");

                    b.ToTable("ScholarshipOfferHistories");
                });

            modelBuilder.Entity("StudentApplicationModel.Models.ScholarshipType", b =>
                {
                    b.Property<int>("ScholarshipTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScholarshipTypeID"));

                    b.Property<decimal>("PaymentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ScholarshipLevelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ScholarshipTypeID");

                    b.ToTable("ScholarshipTypes");
                });

            modelBuilder.Entity("StudentApplicationModel.Models.Sport", b =>
                {
                    b.Property<int>("SportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SportID"));

                    b.Property<string>("SportName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SportID");

                    b.ToTable("Sports", (string)null);
                });

            modelBuilder.Entity("StudentApplicationModel.Models.UserSport", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SportID")
                        .HasColumnType("int");

                    b.HasKey("UserID", "SportID");

                    b.HasIndex("SportID");

                    b.ToTable("UserSports");
                });

            modelBuilder.Entity("Applicant", b =>
                {
                    b.HasOne("StudentApplicationModel.Models.Campus", "Campus")
                        .WithMany()
                        .HasForeignKey("CampusID");

                    b.HasOne("StudentApplicationModel.Models.Scholarship", null)
                        .WithMany("Applicants")
                        .HasForeignKey("ScholarshipID");

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("ContactDetail", b =>
                {
                    b.HasOne("Applicant", "Applicant")
                        .WithOne("ContactDetail")
                        .HasForeignKey("ContactDetail", "ApplicantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("CourseCode", b =>
                {
                    b.HasOne("Applicant", "Applicant")
                        .WithMany("CourseCodes")
                        .HasForeignKey("ApplicantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("HomeDetail", b =>
                {
                    b.HasOne("Applicant", "Applicant")
                        .WithOne("HomeDetail")
                        .HasForeignKey("HomeDetail", "ApplicantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("Referee", b =>
                {
                    b.HasOne("Applicant", "Applicant")
                        .WithMany("Referees")
                        .HasForeignKey("ApplicantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("StudentApplicationModel.Models.ApplicantSport", b =>
                {
                    b.HasOne("Applicant", "Applicant")
                        .WithMany("ApplicantSports")
                        .HasForeignKey("ApplicantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentApplicationModel.Models.Sport", "Sport")
                        .WithMany("ApplicantSports")
                        .HasForeignKey("SportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("StudentApplicationModel.Models.Scholarship", b =>
                {
                    b.HasOne("StudentApplicationModel.Models.ScholarshipType", "ScholarshipType")
                        .WithMany("Scholarships")
                        .HasForeignKey("ScholarshipTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScholarshipType");
                });

            modelBuilder.Entity("StudentApplicationModel.Models.ScholarshipApplication", b =>
                {
                    b.HasOne("Applicant", "Applicant")
                        .WithMany()
                        .HasForeignKey("ApplicantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("StudentApplicationModel.Models.ScholarshipOfferHistory", b =>
                {
                    b.HasOne("Applicant", "Applicant")
                        .WithMany()
                        .HasForeignKey("ApplicantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentApplicationModel.Models.Scholarship", "Scholarship")
                        .WithMany("ScholarshipOfferHistories")
                        .HasForeignKey("ScholarshipID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentApplicationModel.Models.Sport", "Sport")
                        .WithMany("ScholarshipOfferHistories")
                        .HasForeignKey("SportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("Scholarship");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("StudentApplicationModel.Models.UserSport", b =>
                {
                    b.HasOne("StudentApplicationModel.Models.Sport", "Sport")
                        .WithMany("UserSports")
                        .HasForeignKey("SportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("Applicant", b =>
                {
                    b.Navigation("ApplicantSports");

                    b.Navigation("ContactDetail")
                        .IsRequired();

                    b.Navigation("CourseCodes");

                    b.Navigation("HomeDetail")
                        .IsRequired();

                    b.Navigation("Referees");
                });

            modelBuilder.Entity("StudentApplicationModel.Models.Scholarship", b =>
                {
                    b.Navigation("Applicants");

                    b.Navigation("ScholarshipOfferHistories");
                });

            modelBuilder.Entity("StudentApplicationModel.Models.ScholarshipType", b =>
                {
                    b.Navigation("Scholarships");
                });

            modelBuilder.Entity("StudentApplicationModel.Models.Sport", b =>
                {
                    b.Navigation("ApplicantSports");

                    b.Navigation("ScholarshipOfferHistories");

                    b.Navigation("UserSports");
                });
#pragma warning restore 612, 618
        }
    }
}
