// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScholarshipInfoSystem.Data;

#nullable disable

namespace StudentApplicationPages.Migrations
{
    [DbContext(typeof(PrimaryContext))]
    [Migration("20241021142001_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ScholarshipInfoSystem.Models.Applicant", b =>
                {
                    b.Property<int>("ApplicantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicantID"));

                    b.Property<string>("ApplicationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAONumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CampusID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ScholarshipID")
                        .HasColumnType("int");

                    b.HasKey("ApplicantID");

                    b.HasIndex("ScholarshipID");

                    b.ToTable("Applicants");
                });

            modelBuilder.Entity("ScholarshipInfoSystem.Models.ApplicantSport", b =>
                {
                    b.Property<int>("ApplicantID")
                        .HasColumnType("int");

                    b.Property<int>("SportID")
                        .HasColumnType("int");

                    b.HasKey("ApplicantID", "SportID");

                    b.HasIndex("SportID");

                    b.ToTable("ApplicantSports");
                });

            modelBuilder.Entity("ScholarshipInfoSystem.Models.CommitteeMember", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberID");

                    b.ToTable("CommitteeMembers");
                });

            modelBuilder.Entity("ScholarshipInfoSystem.Models.ContactDetail", b =>
                {
                    b.Property<int>("ContactID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactID"));

                    b.Property<int>("ApplicantID")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactID");

                    b.HasIndex("ApplicantID")
                        .IsUnique();

                    b.ToTable("ContactDetails");
                });

            modelBuilder.Entity("ScholarshipInfoSystem.Models.HomeDetail", b =>
                {
                    b.Property<int>("HomeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HomeID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ApplicantID")
                        .HasColumnType("int");

                    b.HasKey("HomeID");

                    b.HasIndex("ApplicantID")
                        .IsUnique();

                    b.ToTable("HomeDetails");
                });

            modelBuilder.Entity("ScholarshipInfoSystem.Models.MemberSport", b =>
                {
                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<int>("SportID")
                        .HasColumnType("int");

                    b.HasKey("MemberID", "SportID");

                    b.HasIndex("SportID");

                    b.ToTable("MemberSports");
                });

            modelBuilder.Entity("ScholarshipInfoSystem.Models.Referee", b =>
                {
                    b.Property<int>("RefereeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefereeID"));

                    b.Property<int>("ApplicantID")
                        .HasColumnType("int");

                    b.Property<string>("RefereeDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RefereeID");

                    b.HasIndex("ApplicantID");

                    b.ToTable("Referees");
                });

            modelBuilder.Entity("ScholarshipInfoSystem.Models.Scholarship", b =>
                {
                    b.Property<int>("ScholarshipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScholarshipID"));

                    b.Property<string>("OtherDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScholarshipTypeID")
                        .HasColumnType("int");

                    b.HasKey("ScholarshipID");

                    b.HasIndex("ScholarshipTypeID");

                    b.ToTable("Scholarships");
                });

            modelBuilder.Entity("ScholarshipInfoSystem.Models.ScholarshipApplication", b =>
                {
                    b.Property<int>("ApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationID"));

                    b.Property<int>("ApplicantID")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ApplicationID");

                    b.HasIndex("ApplicantID");

                    b.ToTable("ScholarshipApplications");
                });

            modelBuilder.Entity("ScholarshipInfoSystem.Models.ScholarshipOfferHistory", b =>
                {
                    b.Property<int>("OfferID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfferID"));

                    b.Property<int>("ApplicantID")
                        .HasColumnType("int");

                    b.Property<int?>("CampusID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OfferDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResponseStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScholarshipID")
                        .HasColumnType("int");

                    b.Property<int>("SportID")
                        .HasColumnType("int");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OfferID");

                    b.HasIndex("ApplicantID");

                    b.HasIndex("ScholarshipID");

                    b.HasIndex("SportID");

                    b.ToTable("ScholarshipOfferHistories");
                });

            modelBuilder.Entity("ScholarshipInfoSystem.Models.ScholarshipType", b =>
                {
                    b.Property<int>("ScholarshipTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScholarshipTypeID"));

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ScholarshipLevelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ScholarshipTypeID");

                    b.ToTable("ScholarshipTypes");
                });

            modelBuilder.Entity("ScholarshipInfoSystem.Models.Sport", b =>
                {
                    b.Property<int>("SportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SportID"));

                    b.Property<string>("SportName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SportID");

                    b.ToTable("Sports");
                });

            modelBuilder.Entity("ScholarshipInfoSystem.Models.Applicant", b =>
                {
                    b.HasOne("ScholarshipInfoSystem.Models.Scholarship", "Scholarship")
                        .WithMany("Applicants")
                        .HasForeignKey("ScholarshipID");

                    b.Navigation("Scholarship");
                });

            modelBuilder.Entity("ScholarshipInfoSystem.Models.ApplicantSport", b =>
                {
                    b.HasOne("ScholarshipInfoSystem.Models.Applicant", "Applicant")
                        .WithMany("ApplicantSports")
                        .HasForeignKey("ApplicantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScholarshipInfoSystem.Models.Sport", "Sport")
                        .WithMany("ApplicantSports")
                        .HasForeignKey("SportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("ScholarshipInfoSystem.Models.ContactDetail", b =>
                {
                    b.HasOne("ScholarshipInfoSystem.Models.Applicant", "Applicant")
                        .WithOne("ContactDetail")
                        .HasForeignKey("ScholarshipInfoSystem.Models.ContactDetail", "ApplicantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("ScholarshipInfoSystem.Models.HomeDetail", b =>
                {
                    b.HasOne("ScholarshipInfoSystem.Models.Applicant", "Applicant")
                        .WithOne("HomeDetail")
                        .HasForeignKey("ScholarshipInfoSystem.Models.HomeDetail", "ApplicantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("ScholarshipInfoSystem.Models.MemberSport", b =>
                {
                    b.HasOne("ScholarshipInfoSystem.Models.CommitteeMember", "CommitteeMember")
                        .WithMany("MemberSports")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScholarshipInfoSystem.Models.Sport", "Sport")
                        .WithMany("MemberSports")
                        .HasForeignKey("SportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommitteeMember");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("ScholarshipInfoSystem.Models.Referee", b =>
                {
                    b.HasOne("ScholarshipInfoSystem.Models.Applicant", "Applicant")
                        .WithMany("Referees")
                        .HasForeignKey("ApplicantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("ScholarshipInfoSystem.Models.Scholarship", b =>
                {
                    b.HasOne("ScholarshipInfoSystem.Models.ScholarshipType", "ScholarshipType")
                        .WithMany("Scholarships")
                        .HasForeignKey("ScholarshipTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScholarshipType");
                });

            modelBuilder.Entity("ScholarshipInfoSystem.Models.ScholarshipApplication", b =>
                {
                    b.HasOne("ScholarshipInfoSystem.Models.Applicant", "Applicant")
                        .WithMany("ScholarshipApplications")
                        .HasForeignKey("ApplicantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("ScholarshipInfoSystem.Models.ScholarshipOfferHistory", b =>
                {
                    b.HasOne("ScholarshipInfoSystem.Models.Applicant", "Applicant")
                        .WithMany("ScholarshipOfferHistories")
                        .HasForeignKey("ApplicantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScholarshipInfoSystem.Models.Scholarship", "Scholarship")
                        .WithMany("ScholarshipOfferHistories")
                        .HasForeignKey("ScholarshipID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScholarshipInfoSystem.Models.Sport", "Sport")
                        .WithMany("ScholarshipOfferHistories")
                        .HasForeignKey("SportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("Scholarship");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("ScholarshipInfoSystem.Models.Applicant", b =>
                {
                    b.Navigation("ApplicantSports");

                    b.Navigation("ContactDetail")
                        .IsRequired();

                    b.Navigation("HomeDetail")
                        .IsRequired();

                    b.Navigation("Referees");

                    b.Navigation("ScholarshipApplications");

                    b.Navigation("ScholarshipOfferHistories");
                });

            modelBuilder.Entity("ScholarshipInfoSystem.Models.CommitteeMember", b =>
                {
                    b.Navigation("MemberSports");
                });

            modelBuilder.Entity("ScholarshipInfoSystem.Models.Scholarship", b =>
                {
                    b.Navigation("Applicants");

                    b.Navigation("ScholarshipOfferHistories");
                });

            modelBuilder.Entity("ScholarshipInfoSystem.Models.ScholarshipType", b =>
                {
                    b.Navigation("Scholarships");
                });

            modelBuilder.Entity("ScholarshipInfoSystem.Models.Sport", b =>
                {
                    b.Navigation("ApplicantSports");

                    b.Navigation("MemberSports");

                    b.Navigation("ScholarshipOfferHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
